### ISSUE TITLE
Investigate and try to remove Fuzi

### ISSUE THREAD

**Issue by chrmod** [cliqz/user-agent-ios#1046]

**Comment by chrmod** [comment]
Have done some investigation and while iOS XMLParser would work as a replacement for Fuzi, it's API is quite cumbersome to use. We can visit this in the future.

**Comment by shahenAnt** [comment]
As iOS XMLParser is parsing data asynchronusly it's is not comfortable to use it know for us. I am going to close this issue becouse we are not going to replace it with native functionality.
