### ISSUE TITLE
Bring back Favicons

### ISSUE THREAD

**Issue by chrmod** [cliqz/user-agent-ios#1049]
Bring back code removed by https://github.com/cliqz/user-agent-ios/pull/240 (and possibly other related commits).

Make it possible for brand to decide if Favicons or Cliqz logos should be used.

**Comment by shahenAnt** [comment]
Please take a look the commit: https://github.com/mozilla-mobile/firefox-ios/commit/1a58eeb7ee03e10d3ab0b17104d0fac4d9375be3
