### ISSUE TITLE
Clean up Page Actions

### ISSUE THREAD

**Issue by winsmith** [cliqz/user-agent-ios#149]
Page Actions is the menu reached by tapping the three dot falafel menu in the URL bar. It is only shown when a page is loaded.

## Removals
- [ ] Remove Home
- [ ] Remove Send to Device (and the FireFox account related viewcontrollers behind the menu item)
- [ ] Remove Share Page With (this lives in the Toolbar now)

## Additions
- [ ] Add Refresh

**Comment by chrmod** [comment]
closing in favor of https://github.com/cliqz/user-agent-ios/issues/151
