### ISSUE TITLE
Onboarding

### ISSUE THREAD

**Issue by chrmod** [cliqz/user-agent-ios#186]
![image (5)](https://user-images.githubusercontent.com/1228153/68403562-6da08e80-017d-11ea-8fee-788f0ea919af.png)
![image (6)](https://user-images.githubusercontent.com/1228153/68404223-7d6ca280-017e-11ea-9721-615cd0de0210.png)

**Comment by chrmod** [comment]
Note that final images and texts are still to come.

**Comment by shahenAnt** [comment]
I need assets and localization to be able to complete this ticket.
