### ISSUE TITLE
"Add search engine" icon broken on iPad

### ISSUE THREAD

**Issue by chrmod** [cliqz/user-agent-ios#363]
![IMG_2D4D56DD31C0-1](https://user-images.githubusercontent.com/1228153/68109024-d8399c00-fee9-11e9-95f6-9dcccad1701e.jpeg)

Steps to reproduce:
* open the app on iPad
* go to google.com
* focus search bar
* type a character
* remove the character (backspace)

**Comment by shahenAnt** [comment]
As this problem is coming from Firefox sources I have opened new issue https://github.com/mozilla-mobile/firefox-ios/issues/5712

**Comment by chrmod** [comment]
This fix is important for https://github.com/cliqz/user-agent-ios/issues/377

**Comment by chrmod** [comment]
Closing as feature was removed
