### ISSUE TITLE
Burn button

### ISSUE THREAD

**Issue by chrmod** [cliqz/user-agent-ios#399]
"Burn" button should be added to Control Center action sheet.

On tab, another action sheet should be shown with two options:
* "Close all tabs and clear data"
* "Cancel"

Choice of "Close all tabs and clear data" should do the following:
* remove all tabs (including private mode)
* remove browsing history
* clearing the caches
* removing the cookies
* removing offline WebSite Data

To get more insight how the clearing part should work, please check the Settings -> Data Management -> Clear Private Data

For functional guideline please check DuckDuckGo Burn button.

Designs have to be provided by @cliqz/alexei-team

**Comment by shahenAnt** [comment]
@chrmod Could you provide Item Title(English/German) and icon.
