### ISSUE TITLE
Onboarding: tracking protection has weird background

### ISSUE THREAD

**Issue by chrmod** [cliqz/user-agent-ios#500]
![Screenshot 2019-11-20 at 09 38 17](https://user-images.githubusercontent.com/1228153/69223154-1afea380-0b7b-11ea-817a-cba5ed98e209.png)

**Comment by shahenAnt** [comment]
@chrmod  Only English version has that problem we need to update the image.
![2C EN](https://user-images.githubusercontent.com/55664114/69405529-6353c800-0d19-11ea-9457-7321a7213513.png)

**Comment by chrmod** [comment]
New assets: 
![2C DE2](https://user-images.githubusercontent.com/1228153/70132948-81a8b480-1685-11ea-8dc7-97cef3f51247.png)
![2C EN2](https://user-images.githubusercontent.com/1228153/70132949-81a8b480-1685-11ea-8149-fd99d935ab12.png)
