### ISSUE TITLE
Make possible downloading known file types

### ISSUE THREAD

**Issue by pavel-cliqz** [cliqz/user-agent-ios#521]
## Expected Behavior
If I open pdf , xls or any other known file type of WKWebview, I want to be able to download those into my storage.

## Actual Behavior
It renders in webpage and no way to download it with Cliqz. You can use share functionality to download it, but 1st it won't appear in your download list. 2nd to much actions required for that. 

## Specifications

  - Version: 3.1.0
  - iOS Device:

**Comment by chrmod** [comment]
related: https://github.com/cliqz/user-agent-ios/issues/731
