### ISSUE TITLE
User feature request: Dark Mode

### ISSUE THREAD

**Issue by elisa-cliqz** [cliqz/user-agent-ios#589]
Dark Mode, separate from whole iOS theme

**Comment by elisa-cliqz** [comment]
https://cliqztix.atlassian.net/wiki/spaces/US/pages/903380994/User+Feature+Requests

**Comment by chrmod** [comment]
As of iOS 13 the Dark Appearance is officially a part of the iOS platform. Cliqz Browser is going to respect the OS settings and there will be now way to manually overwrite them.
