### ISSUE TITLE
User feature request: Change background picture

### ISSUE THREAD

**Issue by elisa-cliqz** [cliqz/user-agent-ios#590]
Option to change background picture

**Comment by elisa-cliqz** [comment]
https://cliqztix.atlassian.net/wiki/spaces/US/pages/903380994/User+Feature+Requests

**Comment by chrmod** [comment]
For starters we could use same images as shown on Cliqz SERP.
https://cdn.cliqz.com/serp/configs/config_23.json

**Comment by chrmod** [comment]
Starting release 3.5 - Home page will have dynamic backgrounds
