### ISSUE TITLE
Ads on Google SERP

### ISSUE THREAD

**Issue by chrmod** [cliqz/user-agent-ios#646]
The rule to remove them should be on the list already but somehow it does not work. It seems that rules does not update at all.

Lets add the google serp rule on top of existing list using this aproach https://github.com/cliqz/user-agent-ios/pull/571

**Comment by aquitaine** [comment]
Not sure if this is 100% solved 

![A9C6D17F-4CC9-4AA7-9286-9C40BAA78EB5](https://user-images.githubusercontent.com/1214863/73018852-55561c80-3e1a-11ea-9b04-b208d7c45784.png)

**Comment by chrmod** [comment]
Definitely still an issue. Thank you for report @aquitaine 

@remusao I guess we have to add another blocklist rule for this class of ads

**Comment by chrmod** [comment]
Looks like new lists cover this case as well. @aquitaine 3.3.0 is going to be release this week. Could you please take a look if it fixes this issue? Closing it for now as it work locally.
