### ISSUE TITLE
Contextual onboarding: Wipe all traces of domain

### ISSUE THREAD

**Issue by chrmod** [cliqz/user-agent-ios#848]
When user will wipe all traces of the domain for the first time, before the cleanup will start we want to present a modal dialog explaing user what is going to happen. Such dialogs will be used in multiple places of the app and should allways look the same.

Dialog will have:
* header
* description
* bullet points
* footer text
* checkbox to prevent showing this kind of modal in the future ("don't show again")
* cancel and ok buttons

![modal-dialog-sketch](https://user-images.githubusercontent.com/1228153/77632153-e302d500-6f4d-11ea-8366-b02737c1c45b.png)

**Comment by alexei-cliqz** [comment]
![image](https://user-images.githubusercontent.com/17572438/78673215-1cd6c280-78e2-11ea-86be-0c9b512bddcc.png)

there are first basic versions

**Comment by chrmod** [comment]
Design exploration

![image (8)](https://user-images.githubusercontent.com/1228153/78806272-bd9caf00-79c2-11ea-9cea-471031d95817.png)

**Comment by chrmod** [comment]
Final design:

![Uploading image (7).png…]()

**Comment by chrmod** [comment]
![image (10)](https://user-images.githubusercontent.com/1228153/78882711-c17b1080-7a58-11ea-91ff-c396f5d6c440.png)
![image (9)](https://user-images.githubusercontent.com/1228153/78882727-c4760100-7a58-11ea-909a-6a6ba6ff2022.png)

**Comment by chrmod** [comment]
[wipe-white.pdf](https://github.com/cliqz/user-agent-ios/files/4455443/wipe-white.pdf)
[wipe.pdf](https://github.com/cliqz/user-agent-ios/files/4455444/wipe.pdf)

**Comment by chrmod** [comment]
Final copy:
```
header: Delete All Website Traces
text: You don't want your boss, spouse or partner to see that you've visited a specific website? Don't worry! Your secret is safe with Cliqz: You can easily delete all traces of this site stored in your browser, including history entries and cookies.
```

**Comment by chrmod** [comment]
German copy:
```
header: Alle Website-Spuren löschen
text: Du möchtest nicht, dass dein Chef oder Partner sieht, dass du eine bestimmte Website besucht hast? Keine Sorge! Dein Geheimnis ist bei Cliqz sicher: Du kannst alle im Browser hinterlassenen Spuren dieser Website ganz einfach löschen, einschließlich Verlaufseinträge und Cookies.
Don't show again = Nicht mehr anzeigen
```
