### ISSUE TITLE
Handle url queries

### ISSUE THREAD

**Issue by chrmod** [cliqz/user-agent-ios#855]
In cases the urlbar has a complete query we should not offer any search engine links, but to open the link directly.

![Image from iOS](https://user-images.githubusercontent.com/1228153/77314888-d7719d00-6d06-11ea-920a-458761e28df9.png)

**Comment by dominiks-cliqz** [comment]
You could add a button "Go to URL" for example.

**Comment by chrmod** [comment]
In the place where "More search results" button is, right? 

Things we could do:
* show website logo (based on logo database)
* check history for website title

**Comment by dominiks-cliqz** [comment]
Let's try using the mixer's `navigate-to` result.

**Comment by alexei-cliqz** [comment]
@chrmod how about such variant?

![image](https://user-images.githubusercontent.com/17572438/80377043-fed5ff80-889a-11ea-96ad-aeaf5c4d7e27.png)
