### ISSUE TITLE
Weather widgets shown on long press on app icon

### ISSUE THREAD

**Issue by chrmod** [cliqz/user-agent-ios#866]
Can we disable widget preview? It is a bit confusing as weather is not what Cliqz is all about.

**Comment by shahenAnt** [comment]
Looks like there is no official way of solving this issue. The only hack which worked to set UIApplicationShortcutWidget as nil in info.plist, but what we can see in the comments  it will cause to app rejection. See info in attached links:
1. https://stackoverflow.com/questions/39558344/disable-ios-10-quick-actions-widget
2. https://stackoverflow.com/questions/39661418/can-you-hide-app-widgets-from-appearing-under-the-3d-touch-quick-actions
